export const MAP_LAYERS_CONFIG = [
  {
    id: 'general',
    layerKey: 'General',
    label: 'Vista general',
    description: 'Integra festivales, escuelas, mercados, redes de documentación y lutieres en una lectura territorial única.',
    color: '#291242',
    defaultVisible: true,
    iconKey: 'layout-grid',
  },
  {
    id: 'festivales',
    layerKey: 'Festivales',
    label: 'Festivales',
    description: 'Procesos y eventos tipo festival registrados en el ecosistema.',
    color: '#16a34a',
    defaultVisible: true,
    iconKey: 'party',
  },
  {
    id: 'mercados',
    layerKey: 'Mercados Musicales',
    label: 'Mercados',
    description: 'Mercados musicales y espacios de circulación/comercialización.',
    color: '#f59e0b',
    defaultVisible: true,
    iconKey: 'building',
  },
  {
    id: 'escuelas',
    layerKey: 'Escuelas de Música',
    label: 'Escuelas',
    description: 'Escuelas y procesos formativos musicales registrados.',
    color: '#0284c7',
    defaultVisible: true,
    iconKey: 'library',
  },
  {
    id: 'redes',
    layerKey: 'Redes de Documentación',
    label: 'Redes Doc.',
    description: 'Redes de documentación e investigación musical.',
    color: '#ec4899',
    defaultVisible: true,
    iconKey: 'book-open',
  },
  {
    id: 'lutieres',
    layerKey: 'Lutieres',
    label: 'Lutieres',
    description: 'Constructores y reparadores de instrumentos musicales.',
    color: '#0ea5e9',
    defaultVisible: true,
    iconKey: 'hammer',
  },
];

export const MAP_PANEL_IDS = {
  layers: 'layers',
  territory: 'territory',
  filters: 'filters',
  insights: 'insights',
  tutorial: 'tutorial',
  export: 'export',
  registration: 'registration',
};
